### ISSUE TITLE
Tests failing with Cannot perform Construct on a detached ArrayBuffer

### ISSUE THREAD

**Issue by miry** [lbguilherme/crystal-js#2]
I made to build and run tests for changes in https://github.com/lbguilherme/crystal-js/pull/1/files. [github action logs](https://github.com/miry/crystal-js/actions/runs/4812513316/jobs/8567848000)

For `deno` it returns:

```
error: Uncaught TypeError: Cannot perform Construct on a detached ArrayBuffer
          crypto.getRandomValues(new Uint8Array(__memory.buffer, buf, len));
                                 ^
    at new Uint8Array (<anonymous>)
    at random_get (file:///tmp/crystal-js-spec.MnKIAS.mjs:214:34)
    at __wasi_random_get (wasm://wasm/00b26d9e:1:1530849)
    at *Crystal::System::Random::random_bytes<Slice(UInt8)>:Nil (wasm://wasm/00b26d9e:1:515273)
    at __crystal_main (wasm://wasm/00b26d9e:1:7418)
    at *Crystal::main_user_code<Int32, Pointer(Pointer(UInt8))>:Nil (wasm://wasm/00b26d9e:1:1517400)
    at *Crystal::main<Int32, Pointer(Pointer(UInt8))>:Int32 (wasm://wasm/00b26d9e:1:1517328)
    at _start (wasm://wasm/00b26d9e:1:135618)
    at init (file:///tmp/crystal-js-spec.MnKIAS.mjs:245:13)
    at async file:///tmp/crystal-js-spec.MnKIAS.mjs:251:3
```

If build also web version it shows next error in console:

<img width="447" alt="image" src="https://user-images.githubusercontent.com/21104/234681292-79534606-d62d-42e0-9b9c-c32f31591955.png">

The line with error:
```
crypto.getRandomValues(new Uint8Array(__memory.buffer, buf, len));
```
and `__memory.buffer` is looks like ```ArrayBuffer { byteLength: 0 }```

I am new to WASM and looking for help how debug such problem and possible fix.

**Comment by miry** [comment]
I believe it is related to https://github.com/emscripten-core/emscripten/issues/6747
With logs in different places `console.log("before start: ", __memory.buffer);`
I identify that the size is 0 for random_get.

<img width="423" alt="image" src="https://user-images.githubusercontent.com/21104/234780059-cb1414fa-5fd5-4430-9a35-807687ff9c78.png">

**Comment by miry** [comment]
The size of buffer looks like increased in my case from to 720896.
Created a PR to hack the problem: https://github.com/lbguilherme/crystal-js/pull/3
